namespace DevOpsRemainingQuery
{
    /// <summary>
    /// Class QuerySettings.
    /// </summary>
    /// <autogeneratedoc/>
    internal class QuerySettings
    {
        /// <summary>
        /// Gets or sets the activity order.
        /// </summary>
        /// <value>The activity order.</value>
        /// <autogeneratedoc/>
#pragma warning disable SA1011 // Closing square brackets should be spaced correctly
        public string[]? ActivityOrder { get; set; }
#pragma warning restore SA1011 // Closing square brackets should be spaced correctly

        /// <summary>
        /// Gets or sets the area path.
        /// </summary>
        /// <value>The area path.</value>
        /// <autogeneratedoc/>
        public string? AreaPath { get; set; }

        /// <summary>
        /// Gets or sets the iteration path.
        /// </summary>
        /// <value>The iteration path.</value>
        /// <autogeneratedoc/>
        public string? IterationPath { get; set; }

        /// <summary>
        /// Gets or sets the output file.
        /// </summary>
        /// <value>The output file.</value>
        /// <autogeneratedoc/>
        public string? OutputFile { get; set; }

        /// <summary>
        /// Gets or sets the maximum parent hierarchy depth.
        /// </summary>
        /// <value>The maximum parent hierarchy depth.</value>
        public int? ParentDepth { get; set; }

        /// <summary>
        /// Gets or sets the personal access token.
        /// </summary>
        /// <value>The personal access token.</value>
        /// <autogeneratedoc/>
        public string? PersonalAccessToken { get; set; }

        /// <summary>
        /// Gets or sets the project.
        /// </summary>
        /// <value>The project.</value>
        /// <autogeneratedoc/>
        public string? Project { get; set; }

        /// <summary>
        /// Gets or sets the query.
        /// </summary>
        /// <value>The query.</value>
        /// <autogeneratedoc/>
        public string? Query { get; set; }

        /// <summary>
        /// Gets or sets the server.
        /// </summary>
        /// <value>The server.</value>
        /// <autogeneratedoc/>
        public string? Server { get; set; }

        /// <summary>
        /// Gets or sets the culture.
        /// </summary>
        /// <value>The culture.</value>
        /// <autogeneratedoc/>
        public string? Culture { get; set; }
    }
}