namespace DevOpsRemainingQuery
{
    /// <summary>
    /// Class QuerySettings.
    /// </summary>
    /// <autogeneratedoc/>
    internal class QuerySettings
    {
        /// <summary>
        /// Gets or sets the area path.
        /// </summary>
        /// <value>The area path.</value>
        /// <autogeneratedoc/>
        public string? AreaPath { get; set; }

        /// <summary>
        /// Gets or sets the iteration path.
        /// </summary>
        /// <value>The iteration path.</value>
        /// <autogeneratedoc/>
        public string? IterationPath { get; set; }

        /// <summary>
        /// Gets or sets the output file.
        /// </summary>
        /// <value>The output file.</value>
        /// <autogeneratedoc/>
        public string? OutputFile { get; set; }

        /// <summary>
        /// Gets or sets the personal access token.
        /// </summary>
        /// <value>The personal access token.</value>
        /// <autogeneratedoc/>
        public string? PersonalAccessToken { get; set; }

        /// <summary>
        /// Gets or sets the project.
        /// </summary>
        /// <value>The project.</value>
        /// <autogeneratedoc/>
        public string? Project { get; set; }

        /// <summary>
        /// Gets or sets the query.
        /// </summary>
        /// <value>The query.</value>
        /// <autogeneratedoc/>
        public string? Query { get; set; }

        /// <summary>
        /// Gets or sets the server.
        /// </summary>
        /// <value>The server.</value>
        /// <autogeneratedoc/>
        public string? Server { get; set; }
    }
}