namespace DevOpsRemainingQuery.DevOps
{
    /// <summary>
    /// Class Effort.
    /// </summary>
    /// <autogeneratedoc/>
    public readonly struct Effort
    {
        /// <summary>
        /// Gets the activity.
        /// </summary>
        /// <value>The activity.</value>
        /// <autogeneratedoc/>
        public string Activity { get; init; }

        /// <summary>
        /// Gets the completed work.
        /// </summary>
        /// <value>The completed work.</value>
        /// <autogeneratedoc/>
        public double CompletedWork { get; init; }

        /// <summary>
        /// Gets the original estimate.
        /// </summary>
        /// <value>The original estimate.</value>
        /// <autogeneratedoc/>
        public double OriginalEstimate { get; init; }

        /// <summary>
        /// Gets the remaining work.
        /// </summary>
        /// <value>The remaining work.</value>
        /// <autogeneratedoc/>
        public double RemainingWork { get; init; }
    }
}