namespace DevOpsRemainingQuery.DevOps
{
    /// <summary>
    /// Class WorkItemFieldType.
    /// </summary>
    /// <autogeneratedoc/>
    public class WorkItemFieldType
    {
        /// <summary>
        /// The activity.
        /// </summary>
        /// <autogeneratedoc/>
        public const string Activity = "Microsoft.VSTS.Common.Activity";

        /// <summary>
        /// The completed work.
        /// </summary>
        /// <autogeneratedoc/>
        public const string CompletedWork = "Microsoft.VSTS.Scheduling.CompletedWork";

        /// <summary>
        /// The original estimate.
        /// </summary>
        /// <autogeneratedoc/>
        public const string OriginalEstimate = "Microsoft.VSTS.Scheduling.OriginalEstimate";

        /// <summary>
        /// The remaining work.
        /// </summary>
        /// <autogeneratedoc/>
        public const string RemainingWork = "Microsoft.VSTS.Scheduling.RemainingWork";

        /// <summary>
        /// The title type.
        /// </summary>
        /// <autogeneratedoc/>
        public const string Title = "System.Title";

        /// <summary>
        /// The work item type.
        /// </summary>
        /// <autogeneratedoc/>
        public const string WorkItemType = "System.WorkItemType";
    }
}